### ISSUE TITLE
Import every scss file from directory

### ISSUE THREAD

**Issue by esaramago** [enesaktay/parcel-sass-boilerplate#1]
It would be great if it was possible to import every scss file from a folder, instead of adding it manually everytime we create a file.

For example:
```
// main.scss
@import 'abstracts/*.scss';
```

I usually do this with Gulp and Webpack. I don't know even if it is possible with Parcel.

**Comment by enesaktay** [comment]
@esaramago sorry for the very late response but I didnt do it on purpose because then parcel decides whether in which sequence everything is going to be imported and in most (of my) cases it should have a specific sequence.
